import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./lib/fontawesome";

const iranyekan = localFont({
  src: [
    {
      path: "../public/Fonts/DIN Alternate Black.ttf",
    },
    {
      path: "../public/Fonts/DIN Alternate Bold.ttf",
    },
    {
      path: "../public/Fonts/DIN Alternate Light.ttf",
    },

    {
      path: "../public/Fonts/DIN Alternate Medium.ttf",
    },
    {
      path: "../public/Fonts/DIN Alternate.ttf",
    },
    {
      path: "../public/Fonts/DIN Black.ttf",
    },
    {
      path: "../public/Fonts/DIN BlackAlternate.ttf",
    },
    {
      path: "../public/Fonts/DIN Light.ttf",
    },
    {
      path: "../public/Fonts/DIN Medium.ttf",
    },
  ],
  variable: "--font-iranyekan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html id="scroll" lang="en">
      <body>{children}</body>
    </html>
  );
}
